language: php
sudo: false
php:
  - '7.0'
install:
  - composer install
  - 'php server/bin/doctrine orm:schema-tool:create'
  - 'php server/bin/fixtures'
cache:
  directories:
    - vendor
services:
  - mysql
env:
  - IS_CI=true
before_script:
  - mysql -e 'create database dbname;'